use std::collections::HashMap;
use crate::config::StyleConfig;
use crate::feature::PropMap;
use crate::style::FeatureStyle;
use super::*;

pub type StyleFn = fn(&PropMap, &StyleConfig) -> FeatureStyle;

/// Build a registry mapping S-57 layer names to their style functions.
pub fn build_registry() -> HashMap<&'static str, StyleFn> {
    let mut m: HashMap<&'static str, StyleFn> = HashMap::new();

    // Complex conditional layers
    m.insert("DEPARE", depare::style_feature);
    m.insert("LIGHTS", lights::style_feature);
    m.insert("BCNCAR", bcncar::style_feature);
    m.insert("BCNLAT", bcnlat::style_feature);
    m.insert("BCNISD", bcnisd::style_feature);
    m.insert("BCNSAW", bcnsaw::style_feature);
    m.insert("BCNSPP", bcnspp::style_feature);
    m.insert("BOYCAR", boycar::style_feature);
    m.insert("BOYLAT", boylat::style_feature);
    m.insert("BOYISD", boyisd::style_feature);
    m.insert("BOYSAW", boysaw::style_feature);
    m.insert("BOYSPP", boyspp::style_feature);
    m.insert("TOPMAR", topmar::style_feature);
    m.insert("OBSTRN", obstrn::style_feature);
    m.insert("WRECKS", wrecks::style_feature);
    m.insert("SOUNDG", soundg::style_feature);
    m.insert("UWTROC", uwtroc::style_feature);
    m.insert("LNDARE", lndare::style_feature);
    m.insert("COALNE", coalne::style_feature);
    m.insert("RESARE", resare::style_feature);
    m.insert("DAYMAR", daymar::style_feature);
    m.insert("HULKES", hulkes::style_feature);
    m.insert("LNDMRK", lndmrk::style_feature);

    // Simple layers
    m.insert("AIRARE", simple::airare);
    m.insert("ACHARE", simple::achare);
    m.insert("ACHBRT", simple::achbrt);
    m.insert("ACHPNT", simple::achpnt);
    m.insert("BERTHS", simple::berths);
    m.insert("BOYINB", simple::boyinb);
    m.insert("BRIDGE", simple::bridge);
    m.insert("BUAARE", simple::buaare);
    m.insert("BUISGL", simple::buisgl);
    m.insert("CANALS", simple::canals);
    m.insert("CAUSWY", simple::causwy);
    m.insert("CBLARE", simple::cblare);
    m.insert("CBLOHD", simple::cblohd);
    m.insert("CBLSUB", simple::cblsub);
    m.insert("CGUSTA", simple::cgusta);
    m.insert("CHKPNT", simple::chkpnt);
    m.insert("CONVYR", simple::convyr);
    m.insert("CRANES", simple::cranes);
    m.insert("CTNARE", simple::ctnare);
    m.insert("CTSARE", simple::ctsare);
    m.insert("CURENT", simple::curent);
    m.insert("DAMCON", simple::damcon);
    m.insert("DISMAR", simple::dismar);
    m.insert("DMPGRD", simple::dmpgrd);
    m.insert("DOCARE", simple::docare);
    m.insert("DRGARE", simple::drgare);
    m.insert("DWRTCL", simple::dwrtcl);
    m.insert("DWRTPT", simple::dwrtpt);
    m.insert("DYKCON", simple::dykcon);
    m.insert("FAIRWY", simple::fairwy);
    m.insert("FNCLNE", simple::fnclne);
    m.insert("FERYRT", simple::feryrt);
    m.insert("FLODOC", simple::flodoc);
    m.insert("FOGSIG", simple::fogsig);
    m.insert("FORSTC", simple::forstc);
    m.insert("FSHFAC", simple::fshfac);
    m.insert("FSHGRD", simple::fshgrd);
    m.insert("GATCON", simple::gatcon);
    m.insert("ICEARE", simple::iceare);
    m.insert("ICNARE", simple::icnare);
    m.insert("ISTZNE", simple::istzne);
    m.insert("LAKARE", simple::lakare);
    m.insert("LAKSHR", simple::lakshr);
    m.insert("LITFLT", simple::litflt);
    m.insert("LITVES", simple::litves);
    m.insert("LNDRGN", simple::lndrgn);
    m.insert("LOGPON", simple::logpon);
    m.insert("LOKBSN", simple::lokbsn);
    m.insert("MARCUL", simple::marcul);
    m.insert("MIPARE", simple::mipare);
    m.insert("MORFAC", simple::morfac);
    m.insert("NAVLNE", simple::navlne);
    m.insert("NEWOBJ", simple::newobj);
    m.insert("OFSPLF", simple::ofsplf);
    m.insert("OILBAR", simple::oilbar);
    m.insert("OSPARE", simple::ospare);
    m.insert("PILBOP", simple::pilbop);
    m.insert("PILPNT", simple::pilpnt);
    m.insert("PIPARE", simple::pipare);
    m.insert("PONTON", simple::ponton);
    m.insert("PRCARE", simple::prcare);
    m.insert("PRDARE", simple::prdare);
    m.insert("PYLONS", simple::pylons);
    m.insert("RADLNE", simple::radlne);
    m.insert("RADRFL", simple::radrfl);
    m.insert("RADRNG", simple::radrng);
    m.insert("RCRTCL", simple::rcrtcl);
    m.insert("RCTLPT", simple::rctlpt);
    m.insert("RDOCAL", simple::rdocal);
    m.insert("RECTRC", simple::rectrc);
    m.insert("RETRFL", simple::retrfl);
    m.insert("RIVERS", simple::rivers);
    m.insert("RTPBCN", simple::rtpbcn);
    m.insert("RUNWAY", simple::runway);
    m.insert("SEAARE", simple::seaare);
    m.insert("SILTNK", simple::siltnk);
    m.insert("SISTAT", simple::sistat);
    m.insert("SISTAW", simple::sistaw);
    m.insert("SLCONS", simple::slcons);
    m.insert("SLOGRD", simple::slogrd);
    m.insert("SNDWAV", simple::sndwav);
    m.insert("SPLARE", simple::splare);
    m.insert("SUBTLN", simple::subtln);
    m.insert("SWPARE", simple::swpare);
    m.insert("TCTLPT", simple::tctlpt);
    m.insert("TSELNE", simple::tselne);
    m.insert("TSEBND", simple::tsebnd);
    m.insert("TSSCRS", simple::tsscrs);
    m.insert("TSSLPT", simple::tsslpt);
    m.insert("TSSRON", simple::tssron);
    m.insert("TSEZNE", simple::tsezne);
    m.insert("TSSBND", simple::tssbnd);
    m.insert("TUNNEL", simple::tunnel);
    m.insert("TWRTPT", simple::twrtpt);
    m.insert("UNSARE", simple::unsare);
    m.insert("WEDKLP", simple::wedklp);

    m
}
