use crate::feature::{PropMap, PropMapExt};

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Functn {
    HarbourMastersOffice = 2,
    CustomOffice = 3,
    HealthOffice = 4,
    Hospital = 5,
    PostOffice = 6,
    Hotel = 7,
    RailwayStation = 8,
    PoliceStation = 9,
    WaterPoliceStation = 10,
    PilotOffice = 11,
    PilotLookout = 12,
    BankOffice = 13,
    HeadquartersForDistrictControl = 14,
    TransitShedWarehouse = 15,
    Factory = 16,
    PowerStation = 17,
    Administrative = 18,
    EducationalFacility = 19,
    Church = 20,
    Chapel = 21,
    Temple = 22,
    Pagoda = 23,
    ShintoShrine = 24,
    BuddhistTemple = 25,
    Mosque = 26,
    Marabout = 27,
    Lookout = 28,
    Communication = 29,
    Television = 30,
    Radio = 31,
    Radar = 32,
    LightSupport = 33,
    Microwave = 34,
    Cooling = 35,
    Observation = 36,
    Timeball = 37,
    Clock = 38,
    Control = 39,
    AirshipMooring = 40,
    Stadium = 41,
    BusStation = 42,
}

pub fn functn(props: &PropMap) -> Vec<Functn> {
    props.get_int_list("FUNCTN").into_iter().filter_map(|i| match i {
        2 => Some(Functn::HarbourMastersOffice),
        3 => Some(Functn::CustomOffice),
        4 => Some(Functn::HealthOffice),
        5 => Some(Functn::Hospital),
        6 => Some(Functn::PostOffice),
        7 => Some(Functn::Hotel),
        8 => Some(Functn::RailwayStation),
        9 => Some(Functn::PoliceStation),
        10 => Some(Functn::WaterPoliceStation),
        11 => Some(Functn::PilotOffice),
        12 => Some(Functn::PilotLookout),
        13 => Some(Functn::BankOffice),
        14 => Some(Functn::HeadquartersForDistrictControl),
        15 => Some(Functn::TransitShedWarehouse),
        16 => Some(Functn::Factory),
        17 => Some(Functn::PowerStation),
        18 => Some(Functn::Administrative),
        19 => Some(Functn::EducationalFacility),
        20 => Some(Functn::Church),
        21 => Some(Functn::Chapel),
        22 => Some(Functn::Temple),
        23 => Some(Functn::Pagoda),
        24 => Some(Functn::ShintoShrine),
        25 => Some(Functn::BuddhistTemple),
        26 => Some(Functn::Mosque),
        27 => Some(Functn::Marabout),
        28 => Some(Functn::Lookout),
        29 => Some(Functn::Communication),
        30 => Some(Functn::Television),
        31 => Some(Functn::Radio),
        32 => Some(Functn::Radar),
        33 => Some(Functn::LightSupport),
        34 => Some(Functn::Microwave),
        35 => Some(Functn::Cooling),
        36 => Some(Functn::Observation),
        37 => Some(Functn::Timeball),
        38 => Some(Functn::Clock),
        39 => Some(Functn::Control),
        40 => Some(Functn::AirshipMooring),
        41 => Some(Functn::Stadium),
        42 => Some(Functn::BusStation),
        _ => None,
    }).collect()
}
