use crate::feature::{PropMap, PropMapExt};

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Topshp {
    ConePointUp = 1,
    ConePointDown = 2,
    Sphere = 3,
    TwoSphere = 4,
    CylinderCan = 5,
    Board = 6,
    XShape = 7,
    UprightCross = 8,
    CubePointUp = 9,
    TwoConesPointToPoint = 10,
    TwoConesBaseToBase = 11,
    RhombusDiamond = 12,
    TwoConesPointsUpward = 13,
    TwoConesPointsDownward = 14,
    BesomPointUp = 15,
    BesomPointDown = 16,
    Flag = 17,
    SphereOverRhombus = 18,
    Square = 19,
    RectangleHorizontal = 20,
    RectangleVertical = 21,
    TrapeziumUp = 22,
    TrapeziumDown = 23,
    TrianglePointUp = 24,
    TrianglePointDown = 25,
    Circle = 26,
    TwoCrossesOneOver = 27,
    TShape = 28,
    TriangleOverCircle = 29,
    CrossOverCircle = 30,
    RhombusOverCircle = 31,
    CircleOverTriangle = 32,
    Other = 33,
}

pub fn topshp(props: &PropMap) -> Option<Topshp> {
    match props.get_int("TOPSHP")? {
        1 => Some(Topshp::ConePointUp),
        2 => Some(Topshp::ConePointDown),
        3 => Some(Topshp::Sphere),
        4 => Some(Topshp::TwoSphere),
        5 => Some(Topshp::CylinderCan),
        6 => Some(Topshp::Board),
        7 => Some(Topshp::XShape),
        8 => Some(Topshp::UprightCross),
        9 => Some(Topshp::CubePointUp),
        10 => Some(Topshp::TwoConesPointToPoint),
        11 => Some(Topshp::TwoConesBaseToBase),
        12 => Some(Topshp::RhombusDiamond),
        13 => Some(Topshp::TwoConesPointsUpward),
        14 => Some(Topshp::TwoConesPointsDownward),
        15 => Some(Topshp::BesomPointUp),
        16 => Some(Topshp::BesomPointDown),
        17 => Some(Topshp::Flag),
        18 => Some(Topshp::SphereOverRhombus),
        19 => Some(Topshp::Square),
        20 => Some(Topshp::RectangleHorizontal),
        21 => Some(Topshp::RectangleVertical),
        22 => Some(Topshp::TrapeziumUp),
        23 => Some(Topshp::TrapeziumDown),
        24 => Some(Topshp::TrianglePointUp),
        25 => Some(Topshp::TrianglePointDown),
        26 => Some(Topshp::Circle),
        27 => Some(Topshp::TwoCrossesOneOver),
        28 => Some(Topshp::TShape),
        29 => Some(Topshp::TriangleOverCircle),
        30 => Some(Topshp::CrossOverCircle),
        31 => Some(Topshp::RhombusOverCircle),
        32 => Some(Topshp::CircleOverTriangle),
        33 => Some(Topshp::Other),
        _ => None,
    }
}
